services:
  - type: web
    name: api-jd
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app.db.init_db import init_db; init_db()"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
